<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Recruitment Analytics Report</title>

    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 12px;
            color: #333;
        }

        h1 {
            margin-bottom: 0;
        }

        h2 {
            margin-top: 5px;
            color: #555;
        }

        .header {
            margin-bottom: 20px;
        }

        .meta {
            margin-top: 10px;
            font-size: 11px;
            color: #777;
        }

        .summary {
            margin: 20px 0;
        }

        .summary table {
            width: 100%;
        }

        .summary td {
            padding: 6px 8px;
            background: #f6f6f6;
            border: 1px solid #ddd;
        }

        table.data {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }

        table.data th {
            background: #f0f0f0;
            padding: 8px;
            text-align: left;
            border: 1px solid #ddd;
        }

        table.data td {
            padding: 8px;
            border: 1px solid #ddd;
        }

        .footer {
            margin-top: 30px;
            font-size: 10px;
            color: #777;
            text-align: center;
        }
    </style>

</head>

<body>

    {{-- HEADER --}}
    <div class="header">

        <h1>Recruitment Analytics Report</h1>
        <h2>{{ $employer->company_name ?? 'Employer' }}</h2>

        <div class="meta">

            Generated On:
            <strong>{{ now()->format('F d, Y h:i A') }}</strong>

            <br>

            Generated By:
            <strong>{{ $user->name }}</strong>
            ({{ $user->email }})

            <br>

            Report Type:
            <strong>Employer Recruitment Analytics</strong>

        </div>

    </div>



    {{-- SUMMARY --}}
    <div class="summary">

        <table>

            <tr>
                <td><strong>Total Job Posts</strong><br>{{ $jobs->count() }}</td>
                <td><strong>Total Applications</strong><br>{{ $totalApplications }}</td>
                <td><strong>Hires This Month</strong><br>{{ $hiresThisMonth }}</td>
                <td><strong>Applicants per Job</strong><br>{{ $avgApplicants }}</td>
            </tr>

        </table>

    </div>



    {{-- JOB PERFORMANCE TABLE --}}
    <h3>Top Performing Jobs</h3>

    <table class="data">

        <thead>
            <tr>
                <th>#</th>
                <th>Job Title</th>
                <th>Industry</th>
                <th>Applications</th>
            </tr>
        </thead>

        <tbody>

            @foreach ($jobs as $index => $job)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td>{{ $job->title }}</td>
                    <td>{{ $job->industry ?? 'N/A' }}</td>
                    <td>{{ $job->applications_count }}</td>
                </tr>
            @endforeach

        </tbody>

    </table>



    {{-- FOOTER --}}
    <div class="footer">

        Report generated from the JobAbroad Recruitment Analytics System.

        Generated for internal recruitment analysis.

    </div>

</body>

</html>
